# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:
  cli:
  extends:
  file: docker-compose-cli.yaml
  service: cli
  command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME} ${DELAY}; sleep infinity' #use $TIMEOUT